# Dependencies
markdown:         redcarpet
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            Ricardo Pereira
tagline:          'Developer'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://blog.ricardopereira.eu
baseurl:          /

author:
  name:           'Ricardo Pereira'
  url:            https://twitter.com/ricardopereiraw

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ricardopereira/blog
