# Dependencies
markdown:         kramdown
redcarpet:
  extensions:     ["tables"]
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ricardo Pereira
tagline:          'Blog'
description:      'the developer'
url:              http://blog.ricardopereira.eu
baseurl:          /

author:
  name:           'Ricardo Pereira'
  url:            https://twitter.com/ricardopereiraw

# Custom vars
personal:         http://ricardopereira.eu

rss:              http://blog.ricardopereira.eu/atom.xml

credits:          'Powered by <a href="http://jekyllrb.com" target="_blank">Jekyll</a> and <a href="http://getpoole.com/" target="_blank">Poole</a>.'

github:
  repo:           https://github.com/ricardopereira/blog
  account:        https://github.com/ricardopereira
